apiVersion: batch/v1
kind: Job
metadata:
  name: ark-cluster-update
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: steam-cmd
          image: ghcr.io/danussi/steamcmd:main
          command:
            - steamcmd
          args:
            - "+force_install_dir"
            - "/data"
            - "+login"
            - "anonymous"
            - "+app_update"
            - "376030"
            - "validate"
            - "+quit"
          volumeMounts:
            - mountPath: /data/server
              name: ark-nexus-server
      volumes:
        - name: ark-nexus-server
          persistentVolumeClaim:
            claimName: ark-nexus-server
