# Default values for ark-orchestrator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hermsi/ark-server
  pullPolicy: IfNotPresent
  tag: "latest"

game:
  name: "Ark Operator"

  anticheat:
    battleye: false
    crossplay: true

  players:
    max: 20
    password: "test"

  admin:
    password: "asldhjaskhdkja"

  events:
    preUpdate:
      backup: true
    onStart:
      update: true
    onStop:
      backup: true
      warn: true

  maps:
    - names:
        title: "The Island"
        map: "TheIsland"
        k8s: "the-island"
      ports:
        game: 7777
        socket: 7778
        listen: 27015
        rcon: 27020
      storage: 
        storageClassName: nfs-client
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi
    - names:
        title: "The Center"
        map: "TheCenter"
        k8s: "the-center"
      ports:
        game: 7779
        socket: 7780
        listen: 27016
        rcon: 27021
      storage:
        type: Filesystem
        storageClassName: nfs-client
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 4Gi

  mods:
