# Default values for ark-orchestrator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hermsi/ark-server
  pullPolicy: IfNotPresent
  tag: "latest"

game:
  name: "Ark Operator"

  anticheat:
    battleye: false
    crossplay: true

  players:
    max: 20
    password: "test"

  admin:
    password: "asldhjaskhdkja"

  events:
    preUpdate:
      backup: true
    onStart:
      update: true
    onStop:
      backup: true
      warn: true

  maps:
    - names:
        title: "The Island"
        map: "TheIsland"
        k8s: "the-island"
      ports:
        game: 7777
        client: 7778
        listen: 27015
        rcon: 27020
      storage: 
        size: 1Gi
        class:

  mods:
    - "44654654"
    - "456465466"
    - "798897979"
