apiVersion: v1
kind: Service
metadata:
  name: ark-cluster-service-the-island
  namespace: ark-orchestrator
  labels:
    app: ark-cluster-service
spec:
  selector:
    app: ark-cluster-deployment-the-island
  type: ClusterIP
  ports:
    - port: 27015
      name: query
      protocol: UDP
    - port: 27020
      name: rcon
      protocol: TCP
    - port: 7777
      name: game
      protocol: UDP
    - port: 7778
      name: raw
      protocol: UDP
