apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-nexus-server
  namespace: ark-orchestrator
spec:
  storageClassName: nfs-client
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-nexus-cluster
  namespace: ark-orchestrator
spec:
  storageClassName: nfs-client
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany