apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-nexus-valguero-save-sotrage
  namespace: ark-orchestrator
spec:
  storageClassName: nfs-client
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-nexus-valguero-backup-sotrage
  namespace: ark-orchestrator
spec:
  storageClassName: nfs-client
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce