apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ark-cluster-storage
  namespace: ark-orchestrator
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 500Gi