apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-cluster-pvc
  namespace: {{ .Release.Namespace }}
spec:
{{- with .Values.game.cluster.storage }}
    {{- toYaml . | nindent 2 }}
{{- end }}
