apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-common-config
  namespace: {{ .Release.Namespace }}
data:
  SERVER_PASSWORD: "{{ .Values.game.players.password }}"
  ADMIN_PASSWORD: "{{ .Values.game.admin.password }}"
  MAX_PLAYERS: "{{ .Values.game.players.max }}"
  UPDATE_ON_START: "{{ .Values.game.events.onStart.update}}"
  BACKUP_ON_STOP: "{{ .Values.game.events.onStop.backup }}"
  WARN_ON_STOP: "{{ .Values.game.events.onStop.warn }}"
  PRE_UPDATE_BACKUP: "{{ .Values.game.events.preUpdate.backup }}"
  ENABLE_CROSSPLAY: "{{ .Values.game.anticheat.crossplay }}"
  DISABLE_BATTLEYE: "{{ not .Values.game.anticheat.battleye }}"
  GAME_MOD_IDS: "{{ join "," .Values.game.mods }}"
  CLUSTER_ID: "{{ .Values.game.cluster.id }}"
  ENABLE_NO_TRANSFER_FROM_FILTERING: "{{ .Values.game.cluster.noTransferFromFiltering }}"
  SERVER_GAME_LOG: "{{ .Values.game.logs.enabled }}"
  SERVER_GAME_LOG_INCLUDE_TRIBE_LOGS: "{{ .Values.game.logs.includeTribe }}"
  MINIMUM_TIME_BETWEEN_INVENTORY_RETRIEVAL: "{{ .Values.game.config.minimumTimeBetweenInventoryRetrieval }}"