{{- range $map := .Values.game.maps }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-map-{{ $map.names.k8s }}-pod
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}-map-{{ $map.names.k8s }}
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-map-{{ $map.names.k8s }}
  serviceName: {{ $.Release.Name }}-map-{{ $map.names.k8s }}-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-map-{{ $map.names.k8s }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: ark
        image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        livenessProbe:
          exec:
            command:
            - runuser -u steam -- /usr/bin/arkmanager status | grep '.*Server\ running.*Yes.*'
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - runuser -u steam -- /usr/bin/arkmanager status | grep '.*Server\ listening.*Yes.*'
          initialDelaySeconds: 5
          periodSeconds: 5
        envFrom:
          - configMapRef:
              name: {{ $.Release.Name }}-common-config
        env:
          - name: SESSION_NAME
            value: "{{ $.Values.game.name }} - {{$map.names.title}}"
          - name: SERVER_MAP
            value: "{{$map.names.map}}"
          - name: GAME_CLIENT_PORT
            value: "{{ $map.ports.game }}"
          - name: UDP_SOCKET_PORT
            value: "{{ $map.ports.socket }}"
          - name: SERVER_LIST_PORT
            value: "{{ $map.ports.listen }}"
          - name: RCON_PORT
            value: "{{ $map.ports.rcon }}"
        ports:
          - containerPort: {{ $map.ports.game }}
            name: game
          - containerPort: {{ $map.ports.socket }}
            name: socket
          - containerPort: {{ $map.ports.listen }}
            name: listen
          - containerPort: {{ $map.ports.rcon }}
            name: rcon
        volumeMounts:
          - name: data
            mountPath: /app
  volumeClaimTemplates:
    - apiVersion: v1	
      kind: PersistentVolumeClaim	
      metadata:
        name: data
      spec:
        {{- with $map.storage }}
            {{- toYaml . | nindent 8 }}
        {{- end }}

---
{{- end}}