{{- range $map := .Values.game.maps }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-map-{{ $map.names.k8s }}-pod
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}-map-{{ $map.names.k8s }}
spec:
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-map-{{ $map.names.k8s }}
  serviceName: {{ $.Release.Name }}-map-{{ $map.names.k8s }}-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-map-{{ $map.names.k8s }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: ark
        image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ $.Release.Name }}-common-config
        env:
          - name: SESSION_NAME
            value: "{{ $.Values.game.name }} - {{$map.names.title}}"
          - name: SERVER_MAP
            value: "{{$map.names.map}}"
          - name: GAME_CLIENT_PORT
            value: "7777"
          - name: UDP_SOCKET_PORT
            value: "7778"
          - name: SERVER_LIST_PORT
            value: "27015"
          - name: RCON_PORT
            value: "27020"
        ports:
          - containerPort: 7777
            name: game
          - containerPort: 7778
            name: socket
          - containerPort: 27015
            name: list
          - containerPort: 27020
            name: rcon
        volumeMounts:
          - name: data
            mountPath: /app
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        {{- with $map.storage }}
            {{- toYaml . | nindent 8 }}
        {{- end }}

---
{{- end}}