apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-game-config
  namespace: {{ .Release.Namespace }}
data:
  Game.ini: |-
    [/script/shootergame.shootergamemode]
    # bDisableGenesisMissions=false
    # bIgnoreStructuresPreventionVolumes=true
    # bGenesisUseStructuresPreventionVolumes=true
    # bShowCreativeMode=false
    # bAutoUnlockAllEngrams=false
    # MaxTribeLogs=1
    # bDisableFriendlyFire=false
    # bUseCorpseLocator=false
    # bDisableStructurePlacementCollision=false
    # bAllowUnlimitedRespecs=false
    # bPvEDisableFriendlyFire=false
    # bFlyerPlatformAllowUnalignedDinoBasing=false
    # bDisableLootCrates=false
    # bIncreasePvPRespawnInterval=false
    # IncreasePvPRespawnIntervalCheckPeriod=300
    # IncreasePvPRespawnIntervalMultiplier=2
    # IncreasePvPRespawnIntervalBaseAmount=60
    # bAutoPvETimer=false
    # bAutoPvEUseSystemTime=false
    # AutoPvEStartTimeSeconds=0
    # AutoPvEStopTimeSeconds=0
    # bPvEAllowTribeWar=true
    # bPvEAllowTribeWarCancel=false
    # MaxAlliancesPerTribe=10
    # FastDecayInterval=30
    # bAllowCustomRecipes=false
    # CustomRecipeEffectivenessMultiplier=1.00000
    # CustomRecipeSkillMultiplier=1.00000
    # bAllowPlatformSaddleMultiFloors=false
    # UseCorpseLifeSpanMultiplier=1.00000
    # GlobalPoweredBatteryDurabilityDecreasePerSecond=4
    # RandomSupplyCratePoints=false
    # OverrideMaxExperiencePointsPlayer=1
    # OverrideMaxExperiencePointsDino=1
    # PlayerHarvestingDamageMultiplier=1.00000
    # CraftingSkillBonusMultiplier=1.00000
    # DinoHarvestingDamageMultiplier=3.20000
    # DinoTurretDamageMultiplier=1.00000
    # WildDinoCharacterFoodDrainMultiplier=1.00000
    # WildDinoTorporDrainMultiplier=1.00000
    # TamedDinoCharacterFoodDrainMultiplier=1.00000
    # TamedDinoTorporDrainMultiplier=1.00000
    # PassiveTameIntervalMultiplier=1.00000
    # ResourceNoReplenishRadiusPlayers=1.00000
    # ResourceNoReplenishRadiusStructures=1.00000
    # BaseTemperatureMultiplier=0.47500
    # GlobalItemDecompositionTimeMultiplier=1.00000
    # GlobalCorpseDecompositionTimeMultiplier=1.00000
    # CraftXPMultiplier=1.00000
    # GenericXPMultiplier=1.00000
    # HarvestXPMultiplier=1.00000
    # KillXPMultiplier=1.00000
    # SpecialXPMultiplier=1.00000
    # StructureDamageRepairCooldown=180
    # PvPZoneStructureDamageMultiplier=6.00000
    # bPassiveDefensesDamageRiderlessDinos=false
    # bLimitTurretsInRange=true
    # LimitTurretsRange=10000
    # LimitTurretsNum=100
    # bHardLimitTurretsInRange=true
    # PreventOfflinePvPConnectionInvincibleInterval=5.00000
    # bDisableDinoRiding=false
    # bDisableDinoTaming=false
    # bUseTameLimitForStructuresOnly=false
    # FastDecayInterval=43200
    # GlobalSpoilingTimeMultiplier=1.00000
    # BabyImprintingStatScaleMultiplier=1.00000
    # BabyImprintAmountMultiplier=1.0
    # MatingIntervalMultiplier=1.00000
    # LayEggIntervalMultiplier=1.00000
    # EggHatchSpeedMultiplier=1.00000
    # BabyMatureSpeedMultiplier=1.00000
    # BabyCuddleIntervalMultiplier=1.00000
    # BabyCuddleGracePeriodMultiplier=1.00000
    # BabyCuddleLoseImprintQualitySpeedMultiplier=1.00000
    # BabyFoodConsumptionSpeedMultiplier=1.00000
    # SupplyCrateLootQualityMultiplier=1.0
    # FishingLootQualityMultiplier=1.00000
    # CropGrowthSpeedMultiplier=1.00000
    # PoopIntervalMultiplier=1.00000
    # CropDecaySpeedMultiplier=1.00000
    # HairGrowthSpeedMultiplier=1.00000
    # KickIdlePlayersPeriod=3600

  GameUserSettings.ini: |-
    # ========= DO NOT ADD ========= #
    # 
    # [/script/engine.gamesession]
    # MaxPlayers=70
    # 
    # [SessionSettings]
    # SessionName=arkforum.de
    #
    # ========= DO NOT ADD ========= #
    #
    #
    # NOTE: 
    # Do not add any settings from above to this file. 
    # These settings are controlled by arkmanager.
    # Feel free to uncomment anything below here.
    #
    [ServerSettings]
    # allowThirdPersonPlayer=0
    # AllowCaveBuildingPvE=0
    # alwaysNotifyPlayerJoined=0
    # alwaysNotifyPlayerLeft=0
    # bAllowFlyerCarryPvE=0
    # bDisableStructureDecayPvE=0
    # DayCycleSpeedScale=1.00000
    # DayTimeSpeedScale=1.00000
    # NightTimeSpeedScale=1.00000
    # DinoCharacterFoodDrainMultiplier=1.00000
    # DinoCharacterHealthRecoveryMultiplier=1.00000
    # DinoCharacterStaminaDrainMultiplier=1.00000
    # DinoCountMultiplier=1.00000
    # DinoDamageMultiplier=1.00000
    # DinoResistanceMultiplier=1.00000
    # globalVoiceChat=0
    # HarvestAmountMultiplier=1.00000
    # HarvestHealthMultiplier=1.00000
    # MaxStructuresInRange=6700
    # noTributeDownloads=0
    # PreventDownloadSurvivors=0
    # PreventDownloadItems=0
    # PreventDownloadDinos=0
    # PlayerCharacterFoodDrainMultiplier=1.00000
    # PlayerCharacterHealthRecoveryMultiplier=1.00000
    # PlayerCharacterStaminaDrainMultiplier=1.00000
    # PlayerCharacterWaterDrainMultiplier=1.00000
    # PlayerDamageMultiplier=1.00000
    # PlayerResistanceMultiplier=1.00000
    # proximityChat=0
    # ResourceNoReplenishRadiusPlayers=1.00000
    # ResourceNoReplenishRadiusStructures=1.00000
    # ResourcesRespawnPeriodMultiplier=1.00000
    # ServerAdminPassword=
    # ServerCrosshair=0
    # serverForceNoHud=0
    # serverHardcore=0
    # ServerPassword=
    # serverPVE=0
    # ShowMapPlayerLocation=0
    # StructureDamageMultiplier=1.00000
    # StructureResistanceMultiplier=1.00000
    # TamedDinoDamageMultiplier=1.00000
    # TamedDinoResistanceMultiplier=1.00000
    # TamingSpeedMultiplier=1.00000
    # XPMultiplier=1.00000
    # EnablePVPGamma=0
    # EnablePVEGamma=0
    # SpectatorPassword=
    # DifficultyOffset=0.50000
    # PvEStructureDecayPeriodMultiplier=1.00000
    # PvEStructureDecayDestructionPeriod=1.00000
    # Banlist="http://arkdedicated.com/banlist.txt"
    # PvPStructureDecay=0
    # DisableDinoDecayPvE=0
    # PvEDinoDecayPeriodMultiplier=1.00000
    # AdminLogging=0
    # MaxTamedDinos=8000
    # MaxNumbersofPlayersInTribe=2
    # BattleNumOfTribestoStartGame=2
    # TimeToCollapseROD=100
    # BattleAutoStartGameInterval=100
    # BattleSuddenDeathInterval=300
    # KickIdlePlayersPeriod=1800
    # PerPlatformMaxStructuresMultiplier=1.00000
    # StructureDamageRepairCooldown=180
    # bForceAllStructureLocking=1
    # AutoDestroyOldStructuresMultiplier=0.00000
    # bUseVSync=0
    # MaxPlatformSaddleStructureLimit=100
    # bPassiveDefensesDamageRiderlessDinos=1
    # RCONPort=27020
    # AutoSavePeriodMinutes=20
    # RCONServerGameLogBuffer=600
    # OverrideStructurePlatformPrevention=0
    # PreventOfflinePvPInterval=60.0
    # bPvPDinoDecay=1
    # bPvPStructureDecay=1
    # DisableImprintDinoBuff=1
    # AllowAnyoneBabyImprintCuddle=1
    # EnableExtraStructurePreventionVolumes=1
    # ShowFloatingDamageText=1
    # DestroyUnconnectedWaterPipes=0
    # OverrideOfficialDifficulty=1.0
    # TheMaxStructuresInRange=10500
    # MinimumDinoReuploadInterval=0
    # PvEAllowStructuresAtSupplyDrops=0
    # NPCNetworkStasisRangeScalePlayerCountStart=70
    # NPCNetworkStasisRangeScalePlayerCountEnd=120
    # NPCNetworkStasisRangeScalePercentEnd=0.50
    # MaxPersonalTamedDinos=500
    # AutoDestroyDecayedDinos=1
    # ClampItemSpoilingTimes=0
    # UseOptimizedHarvestingHealth=1
    # AllowCrateSpawnsOnTopOfStructures=1
    # ForceFlyerExplosives=0
    # PreventOfflinePvP=1
    # AllowFlyingStaminaRecovery=1
    # AllowMultipleAttachedC4=1
    # OxygenSwimSpeedStatMultiplier=1.00
    # bPvEDisableFriendlyFire=1
    # ServerAutoForceRespawnWildDinosInterval=86400
    # DisableWeatherFog=0
    # RandomSupplyCratePoints=0
    # CrossARKAllowForeignDinoDownloads=0
    # PersonalTamedDinosSaddleStructureCost=19


    [MessageOfTheDay]
    # Duration=30
    # Message=arkforum.de