{{- range $map := .Values.game.maps }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Release.Name }}-map-{{ $map.names.k8s }}-pod
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}-map
spec:
  containers:
  - name: ark
    image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
    imagePullPolicy: {{ $.Values.image.pullPolicy }}
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
    envFrom:
      - configMapRef:
          name: {{ $.Release.Name }}-common-config
    env:
      - name: SESSION_NAME
        value: "{{ $.Values.game.name }} - {{$map.names.title}}"
      - name: SERVER_MAP
        value: "{{$map.names.map}}"
      - name: GAME_CLIENT_PORT
        value: "7777"
      - name: UDP_SOCKET_PORT
        value: "7778"
      - name: SERVER_LIST_PORT
        value: "27015"
      - name: RCON_PORT
        value: "27020"
      - name: ARK_SERVER_VOLUME
        value: "/app"
    ports:
      - containerPort: 7777
        name: game
      - containerPort: 7778
        name: socket
      - containerPort: 27015
        name: list
      - containerPort: 27020
        name: rcon
    volumeMounts:
      - name: ark-data
        mountPath: /app
      - name: ark-manager
        mountPath: /etc/arkmanager
  volumes:
    - name: ark-data
      persistentVolumeClaim:
        claimName: {{ $.Release.Name }}-map-{{ $map.names.k8s }}-pvc
    - name: ark-manager
      emptyDir:
        medium: Memory
        sizeLimit: 3Gi
---
{{- end}}
