{{- range $map := .Values.game.maps }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ $.Release.Name }}-map-{{ $map.names.k8s }}-pod
  namespace: {{ $.Release.Namespace }}
spec:
  containers:
  - name: ark
    image: {{ $.Values.image.repository }}:{{ $.Values.image.tag }}
    imagePullPolicy: {{ $.Values.image.pullPolicy }}
    securityContext:
      runAsUser: 0
      fsGroup: 0
    envFrom:
      - configMapRef:
          name: {{ $.Release.Name }}-common-config
    env:
      - name: SESSION_NAME
        value: "{{ $.Values.game.name }} - {{$map.names.title}}"
      - name: SERVER_MAP
        value: "{{$map.names.map}}"
      - name: GAME_CLIENT_PORT
        value: "{{ $map.ports.game }}"
      - name: UDP_SOCKET_PORT
        value: "{{ $map.ports.client }}"
      - name: SERVER_LIST_PORT
        value: "{{ $map.ports.listen }}"
      - name: RCON_PORT
        value: "{{ $map.ports.rcon }}"
    ports:
      - containerPort: {{ $map.ports.game }}
        name: game
      - containerPort: {{ $map.ports.client }}
        name: client
      - containerPort: {{ $map.ports.listen }}
        name: list
      - containerPort: {{ $map.ports.rcon }}
        name: rcon
    volumeMounts:
      - name: data
        mountPath: /app
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: {{ $.Release.Name }}-map-{{ $map.names.k8s }}-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-map-{{ $map.names.k8s }}-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  {{- with $map.storage }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end}}
